### ISSUE TITLE
Add variable: repository.escaped_windows_path

### ISSUE THREAD

**Issue by gabriel-vanca** [coenm/RepoM#168]
An `repository.escaped_windows_path` variable should be added that escapes the `\` character.
Example: `d:\\path\\to\\repo`

`repository.location` should also get the same treatment as `repository.path`: It needs a `repository.linux_location` and `repository.escaped_windows_location`.

**Comment by coenm** [comment]
I know what you mean. But what about:

- windows_path_with_ending_slash
- windows_path_without_ending_slash
- linux_path_with_ending_slash
- linux_path_without_ending_slash
- uppercase_path_..

etc.

My point its there are always other derivations of a property. Implementing such properties is in my opinion a tradeoff between usability vs cluttering.

At this point, I'm not convinced we should have such property. Especially because the [`string`](https://github.com/scriban/scriban/blob/master/doc/builtins.md#string-functions) methods of Scriban can provide

**Comment by gabriel-vanca** [comment]
That's a fair point. I'd suggest then deprecating windows_path and linux_path so that repository.path and repository.location are treated equally.
I doubt any Windows app needs linux_path so I'm guessing this is just leftover from RepoZ's MacOS implementation. And if it does, Scriban can be used.

**Comment by coenm** [comment]
True, but those are already in RepoM and removing them would mean a breaking change and at this moment, I'm not willing to do this.
Don't get me wrong,  you are making a valid point and it's likely to be removed in the future but just not now.

Although it looks like you know your way around the yaml action menu's here is a snippet for your request:

```yaml
context:
- type: evaluate-script@1
  content: |-
    repository.escaped_windows_path = string.escape repository.windows_path;

action-menu:
- type: just-text@1
  name: '{{ repository.escaped_windows_path }}'  
- type: just-text@1
  name: '{{ repository.windows_path }}'
